dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - lcov
cache: yarn
env:
  - npm_config_debug=yes
before_script: yarn lint
after_success:
  - yarn global add codacy-coverage
  - nyc report --reporter=text-lcov | codacy-coverage -l js
  - lcov -c -b src/ -d build/ --no-external | codacy-coverage -l cpp
