sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
  - "8"
  - "9"
before_install: sudo apt-get update && sudo apt-get install lcov -y
before_script: npm install -g coveralls node-gyp
after_success:
  - node-gyp --debug rebuild
  - npm test
  - lcov -c -d . --no-external -o lcov-cpp.info
  - lcov -r lcov-cpp.info "*/node_modules/*" -o lcov-cpp.info
  - lcov -a lcov-cpp.info -a coverage/lcov.info -o lcov.info
  - coveralls < lcov.info
