sudo: required
dist: trusty
language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - node
matrix:
  allow_failures:
    - node_js: "4.0"
    - node_js: "4.1"
    - node_js: "4.2"
    - node_js: "4.3"
before_install: sudo apt-get update && sudo apt-get install lcov -y
before_script: npm install -g coveralls node-gyp
after_success:
  - npm run benchmark
  - node-gyp --debug rebuild
  - npm test -- --coverage --coverage-report=lcov
  - lcov -c -d . --no-external -o lcov-cpp.info
  - lcov -r lcov-cpp.info "*/node_modules/*" -o lcov-cpp.info
  - lcov -a lcov-cpp.info -a coverage/lcov.info -o lcov.info
  - coveralls < lcov.info
