sudo: required
dist: trusty
language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - node
cache: apt
before_install: sudo apt-get update && sudo apt-get install lcov -y
before_script: npm install -g coveralls jscoverage node-gyp
after_success:
  - jscoverage index.js && node-gyp --debug rebuild
  - COVERAGE=ON nodeunit --reporter=lcov test.spec.js > lcov-js.info
  - lcov -c -d . --no-external -o lcov-cpp.info
  - lcov -r lcov-cpp.info "*/node_modules/*" -o lcov-cpp.info
  - lcov -a lcov-cpp.info -a lcov-js.info -o lcov.info
  - coveralls < lcov.info
