dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "11"
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - lcov
env:
  - npm_config_debug=yes
before_install: npm install -g codacy-coverage node-gyp nyc
script: nyc npm test && npm run test-ts
after_success:
  - nyc report --reporter=text-lcov | codacy-coverage -l js
  - lcov -c -b src/ -d build/ --no-external | codacy-coverage -l cpp
